import { escapeHtml as e } from "./monthly";
import { monthlyStyles } from "./monthly-style";
import { goodwillLogo } from "./monthly-brand";
import { bars, marketplaceColors } from "./monthly-charts";
import { dataLabel, formatReportValue, kpiMeaning, monthName, pillarNames, type ReportKpi } from "./monthly-content";
import { previousPeriod } from "../lib/views/dates";
import { brandedWorkbook } from "./branded-workbook";
import { metricReadingNote, statusName, workbookNumberFormat, type ReportModel } from "./profile-model";
import type { Section } from "./profiles";

const money = (n: number | null) => formatReportValue(n, "cents");
function metric(k: ReportKpi, value = k.value): string {
  return formatReportValue(value, k.unit) + (value === null ? "" : k.unit === "cents" ? " USD" : k.unit === "cents_per_hour" ? " USD/h" : k.unit === "days" ? " days" : "");
}
function scoreLabel(k: ReportKpi): string {
  const short: Record<string, string> = { revenue_per_labor_hour: "Revenue per labor hour", listings_per_employee: "Listings per employee", days_donation_to_listing: "Donation to listing", avg_selling_price: "Average price per item", sales_per_employee: "Revenue per employee", top10_categories_revenue: "Top 10 categories: revenue", top10_categories_margin: "Top 10 categories: margin amount", repeat_buyer_rate: "Buyers with repeat purchases" };
  return `${short[k.id] ?? kpiMeaning(k).name}${k.anchor2027 ? " *" : ""}${k.unit === "cents" ? " (USD)" : k.unit === "cents_per_hour" ? " (USD/hour)" : k.unit === "days" ? " (days)" : k.unit === "ratio" ? " (average)" : ""}`;
}
const table = (headers: string[], rows: string[][], widths?: number[]) => `<table class="kpi-table">${widths ? `<colgroup>${widths.map(w => `<col style="width:${w}%">`).join("")}</colgroup>` : ""}<thead><tr>${headers.map(h => `<th>${e(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(v => `<td>${e(v)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;

/** Select sections inside the approved monthly template, without separate role templates. */
export function profileReportHtml(m: ReportModel): string {
  const s = m.snapshot, { profile, frequency, period, access } = s.plan, config = profile.reports[frequency];
  const daily = frequency === "daily", finance = config.pages.flat().includes("reconciliation");
  const factCards = () => `<div class="fact-grid">${m.facts.slice(0, 3).map(f => `<article><h4>${e(f.label)}</h4><span class="number">${e(f.unit === "cents" ? money(f.value) : f.value === null ? "Not available" : f.value.toLocaleString("en-US"))}</span><span class="measure-unit">${f.unit === "cents" ? "USD" : "count"}</span><p>${e(f.note)}</p></article>`).join("")}</div>${m.facts.slice(3).map(f => `<p class="caption-note"><strong>${e(f.label)}: ${e(money(f.value))} USD.</strong> ${e(f.note)}</p>`).join("")}`;
  function section(name: Section): string {
    switch (name) {
      case "overview": return `${factCards()}<div class="summary"><h3>At a glance</h3><ul>${m.highlights.map(h => `<li>${e(h)}</li>`).join("")}</ul></div>`;
      case "trend": {
        if (!m.comparisons.length) return "<h3>Comparison</h3><p>A comparable prior period is unavailable.</p>";
        const rows = [{ label: m.comparisons[0].currentLabel, value: m.comparisons[0].current, display: money(m.comparisons[0].current) }, ...m.comparisons.map(c => ({ label: c.baselineLabel.replace("the seven-day average", "Prior 7-day average"), value: c.baseline, display: money(c.baseline) }))];
        return `<h3>Revenue compared with the reference period</h3>${bars("Revenue comparison in USD", rows)}<p class="caption-note">USD. ${e(m.comparisons.map(c => c.note).filter(Boolean).join(" "))} Comparison bases and daily inputs are in Excel.</p>`;
      }
      case "priorities": return `<section class="priorities"><h3>Three priorities for 2027</h3>${m.kpis.filter(k => k.anchor2027).map(k => `<article class="priority"><div><h4>${e(kpiMeaning(k).name)}<span class="technical">${e(k.label)}</span></h4><p>${e(k.id === "net_margin_pct" ? "Revenue remaining after included shipping, other charges and assumed labor costs. General overhead excluded; not final profit." : kpiMeaning(k).meaning)}</p></div><div class="priority-result"><span class="number">${e(metric(k))}</span><span class="comparison">${e(monthName(previousPeriod(period)))}: ${e(metric(k, k.previous))}</span><span class="target">Unapproved source target: ${k.target === null ? "Not set" : e(metric(k, k.target))}</span><span class="data-label">${e(dataLabel(k))}</span></div></article>`).join("")}</section>`;
      case "channels": {
        if (config.channelView === "mix") return `<h3>Where the money came from</h3>${bars("Reported revenue by marketplace in USD", [...m.channels].sort((a,b) => (b.current ?? 0) - (a.current ?? 0)).map(c => ({label:c.label, value:c.current, display:money(c.current), color:marketplaceColors[c.id]})))}<p class="caption-note">USD. ${m.partialDay ? "Partial day; full-day comparisons are deferred." : "Reported amounts for the selected day."} Full figures and source references are in Excel.</p>`;
        if (config.channelView === "changes") {
          const moved = [...m.channels].filter(c => c.change !== null).sort((a, b) => Math.abs(b.change!) - Math.abs(a.change!))[0];
          return `<h3>Which channels contributed to the revenue change?</h3>${bars("Revenue change by reporting group in USD", m.channels.map(c => ({ label: c.label, value: c.change, color: marketplaceColors[c.id], display: c.change === null ? "Unavailable" : `${c.change > 0 ? "+" : ""}${money(c.change)}` })))}<p class="caption-note">USD change from ${e(monthName(previousPeriod(period)))}. ${moved ? `${e(moved.label)} had the largest absolute change (${e(money(moved.change))} USD).` : "Comparable channel values are unavailable."} These are mathematical contributions, not confirmed causes. Current and prior amounts are in Excel.</p>`;
        }
        return `<h3>Which channels changed?</h3>${bars("Revenue by reporting group in USD", m.channels.map(c => ({ label: c.label, value: c.current, display: money(c.current) })))}${table(["Reporting group", daily ? "Previous day (USD)" : "Previous month (USD)", "Change (USD)", daily ? "Customers today" : "Coverage"], m.channels.map(c => [c.label, money(c.previous), money(c.change), daily ? c.customers === null ? "Unavailable" : String(c.customers) : c.note.startsWith("Partial") ? "Partial" : "Reported"]), [34, 22, 22, 22])}<p class="caption-note">${daily ? "Source-defined customer counts can include transaction-based fallbacks; they are not unique people across channels. Previous-week comparison inputs are in Excel." : "Amounts sum daily reporting groups. Daily customer counts are not added to infer unique monthly buyers."}</p>`;
      }
      case "categories": {
        const limit = config.categoryLimit ?? 6;
        const ranked = [...m.categories].sort((a, b) => b.revenueCents - a.revenueCents), total = ranked.reduce((n, c) => n + c.revenueCents, 0);
        const gap = m.facts.find(f => f.unit === "cents")?.value;
        return `<h3>Which categories generated the most revenue?</h3>${ranked.length ? bars("Leading categories by supplied net revenue", ranked.map(c => ({ label: c.category, value: c.revenueCents, display: money(c.revenueCents) })), limit) : "<p>Category records are unavailable.</p>"}<p class="caption-note">USD. Up to ${limit} leading categories are shown; all ${ranked.length} supplied categories are in Excel.</p><aside class="coverage"><h4>Understand the coverage</h4><p>Supplied categories total <strong>${e(money(total))} USD</strong>. ${gap == null ? "" : `Total revenue less category revenue is ${e(money(gap - total))} USD. `}${access.scope.kind === "channel" ? "Amounts group only the channel records returned by the source, including unassigned categories." : "Category figures cover orders with a category. This difference compares coverage, not months; no balancing adjustment has been made."}</p></aside>`;
      }
      case "operations": return `<h3>Changes in listing and inventory flow</h3><div class="changes-list">${m.kpis.filter(k => ["listings_created", "unlisted_backlog", "unsold_inventory_pct"].includes(k.id)).map(k => `<article><h4>${e(kpiMeaning(k).name)}</h4><p>${e(metric(k))}; ${e(monthName(previousPeriod(period)))}: ${e(metric(k, k.previous))}. ${e(kpiMeaning(k).meaning)} ${e(dataLabel(k))}.</p></article>`).join("") || "<p>No scoped operating indicators are available.</p>"}</div><p class="next-section">Observed changes do not establish causes. Detailed values and reading notes are in Excel.</p>`;
      case "scorecard": {
        const rows = Object.entries(pillarNames).map(([pillar, label]) => {
          const members = m.kpis.filter(k => k.pillar === pillar);
          return members.length ? `<tr class="group-heading"><th colspan="5">${e(label)}</th></tr>${members.map(k => `<tr><th scope="row">${e(scoreLabel(k))}</th><td class="numeric">${e(formatReportValue(k.value, k.unit))}</td><td class="numeric">${e(formatReportValue(k.previous, k.unit))}</td><td class="numeric">${k.target === null ? "Not set" : e(formatReportValue(k.target, k.unit))}</td><td>${e(dataLabel(k).replace(" inputs", "").replace("Data ", ""))}</td></tr>`).join("")}` : "";
        }).join("");
        return `<p class="caption-note">* 2027 priority. Targets are unapproved source examples; higher is not always better.</p><table class="kpi-table"><colgroup><col style="width:39%"><col style="width:16%"><col style="width:16%"><col style="width:16%"><col style="width:13%"></colgroup><thead><tr><th>Measure</th><th>${e(m.periodLabel)}</th><th>${e(monthName(previousPeriod(period)))}</th><th>Source target</th><th>Data</th></tr></thead><tbody>${rows}</tbody></table><p class="legend">Calculated = computable from supplied data, not real or positive performance. Simulated = synthetic inputs. Unavailable = missing, not zero.</p><section class="notes"><h3>Essential reading notes</h3><ul>${m.kpis.filter(k => ["revenue_growth_pct", "top10_categories_margin", "repeat_buyer_rate"].includes(k.id)).map(k => `<li>${e(k.id === "revenue_growth_pct" ? metricReadingNote(k, period) + ". The previous growth rate reference is unconfirmed." : k.id === "top10_categories_margin" ? "Category margin excludes customer shipping. Category rankings and amounts are in Excel." : "Repeat buyers are identified within each marketplace, not unique people across the organization.")}</li>`).join("")}</ul></section>`;
      }
      case "readiness": {
        if (access.scope.kind === "channel") return `<aside class="coverage"><h4>What still needs confirmation?</h4><p>Source completeness, customer counts, inventory and pending items are not available through a channel-scoped view. No company-wide substitute is shown. Excel contains the returned channel records and their source references.</p></aside>`;
        const rows = m.sourceRows.filter(r => r.status !== "Received" && (finance || r.status !== "Not due"));
        if (!finance && !rows.length) return `<p class="caption-note"><strong>Source status:</strong> no source is marked missing or needing review in the monthly assessment${s.sourceAsOf ? ` through ${e(s.sourceAsOf)}` : ""}. This does not establish daily completeness. All source files are in Excel.</p>`;
        return `${finance ? `${factCards()}<h3>Source checklist: exceptions to receipt</h3>` : "<h3>Sources needing attention</h3>"}<p class="caption-note">Monthly assessment${s.sourceAsOf ? ` through ${e(s.sourceAsOf)}` : " retrieved at generation"}. Receipt alone does not confirm complete or approved data. Excel lists all sources and individual files${daily ? `, including their business dates` : ""}.</p>${rows.length ? table(["Source", "Monthly status", "Frequency", "Open issues"], rows.slice(0, 6).map(r => [r.name, r.status, r.frequency, String(r.exceptions)]), [43, 23, 18, 16]) + (rows.length > 6 ? `<p class="caption-note">Six of ${rows.length} sources needing review or not yet due are shown; all are in Excel.</p>` : "") : "<p>No source is currently marked missing or needing review in this monthly assessment.</p>"}`;
      }
      case "exceptions": {
        const open = s.exceptions.filter(r => r.status === "open"), shown = open.slice(0, daily ? 2 : 3);
        return `<h3>Pending items to review</h3>${shown.length ? table(["Source / responsible", "Supplied exception"], shown.map(r => [`${r.sourceName ?? "Source unassigned"}\n${r.owner ?? "Owner not supplied"}`, r.message]), [34, 66]) : "<p>The retrieved register has no open exceptions. This does not prove accounting approval.</p>"}<p class="caption-note">${shown.length} of ${open.length} open items shown; Excel retains all ${s.exceptions.length} supplied exception records. The register reflects retrieval time, not a reconstructed historical state.</p>`;
      }
      case "reconciliation": return `<h3>Do the supplied revenue totals agree?</h3>${table(["Revenue cross-check", "USD"], [["Shared sales-view revenue", money(m.reconciliation.reference)], ["Sum of normalized net order lines", money(m.reconciliation.records)], ["Order lines less sales view", money(m.reconciliation.difference)]], [72, 28])}<p class="caption-note">${e(m.reconciliation.note)}</p>`;
      case "close": {
        const c = s.close;
        if (!c) return "<h3>Accounting close</h3><p>The source does not supply close evidence for this period.</p>";
        return `<h3>What is the actual close state?</h3><aside class="coverage"><h4>${e(statusName(c.status))}</h4><p>${c.approvedAt ? `The API records approval at ${e(c.approvedAt)} (UTC).` : "No approval timestamp was supplied."} An exported file does not establish posting in Business Central.</p></aside>${table(["Supplied close evidence", "Value"], [["Journal lines", String(c.journalLines)], ["Lines using placeholder accounts", String(c.placeholderLines)], ["Journal document references", String(c.documents.length)], ["Open items in close summary", String(c.openExceptions)], ["Invoice reference", c.invoice?.reference ?? "Not supplied"], ["Invoice total (USD)", money(c.invoice?.totalCents ?? null)]], [66, 34])}<p class="caption-note">Journal and invoice references are in Excel. Close-summary counts and the current exception register may reflect different states. No accounting entries are created by this report.</p>`;
      }
    }
  }
  const titles: Partial<Record<Section, string>> = { channels: "Where revenue came from", categories: "What changed?", scorecard: config.scorecardTitle ?? (config.kpis === "core" ? "The 15 core indicators" : "Selected operating indicators"), reconciliation: "Reconciliation and close", readiness: "Data readiness" };
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; font-src data:; style-src 'unsafe-inline'; base-uri 'none'"><title>Goodwill ${e(m.title)} | ${e(m.periodLabel)} | ${e(m.scopeLabel)}</title><style>${monthlyStyles}
  .fact-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:20px;margin:14px 0}.fact-grid article{border:1px solid var(--line);border-top:3px solid var(--blue);border-radius:10px;padding:12px}.fact-grid .number{display:block;color:var(--blue);font-size:27px}.fact-grid p{font-size:12px;margin-top:7px}.profile-caption{font-size:12px;color:var(--muted);margin-top:4px}.scope-notice{font-size:12px;border-left:3px solid var(--blue);padding:7px 10px;background:#f5f7fa;margin:12px 0} .report-page>h3:first-of-type{margin-top:10px}
  @media print{.fact-grid .number{font-size:21pt}.fact-grid p,.profile-caption,.scope-notice{font-size:9pt}.fact-grid{gap:16px} .daily .kpi-table{font-size:9pt}.daily .kpi-table td,.daily .kpi-table th{padding:4px 5px}}
  @media screen and (max-width:650px){main{padding:18px;margin:0}.fact-grid,.priorities{grid-template-columns:1fr}.page-heading h1,.page-heading h2{font-size:21px}.page-number{display:none}}
  </style></head><body><main class="${daily ? "daily" : "monthly"}">${config.pages.map((sections, i) => `<section class="report-page"><header class="page-heading"><img class="brand-logo" src="${goodwillLogo}" width="115.6" height="160.6" alt="Official Goodwill logo"><div><p class="organization">Goodwill Industries of Michiana, Inc.</p><h${i ? "2" : "1"}>${e(i ? titles[sections[0]] ?? m.title : m.title)}</h${i ? "2" : "1"}><p class="period">${e(m.periodLabel)} &middot; ${e(m.scopeLabel)}</p><p class="profile-caption">${e(profile.label)} &middot; Proposed profile</p></div><span class="page-number">${i + 1} / ${config.pages.length}</span></header>${i === 0 ? `<p class="eyebrow">${e(profile.purpose[frequency])}</p><aside class="scope-notice"><strong>Prototype · synthetic data.</strong> Roles and access are illustrative, not Goodwill-approved. ${access.scope.kind === "channel" ? "Channel feed completeness is unconfirmed." : "Missing values are not zero."}</aside>` : ""}${sections.map(section).join("")}<footer>Prototype &middot; Mission Control &middot; USD &middot; ${e(s.version)}<br>Generated ${e(s.generatedAt)} (UTC). Synthetic demonstration; not an approved publication.</footer></section>`).join("")}</main></body></html>`;
}

export async function profileWorkbook(m: ReportModel): Promise<Uint8Array> {
  const writer = brandedWorkbook({ periodLabel: m.periodLabel, unit: "USD", generatedAt: m.snapshot.generatedAt, version: m.snapshot.version, profile: m.snapshot.plan.profile.label, scope: m.scopeLabel, freezeHeaders: true });
  for (const spec of m.sheets) {
    const ws = writer.sheet(spec.name, spec.title, `Synthetic prototype. ${spec.note}`, spec.columns.map(c => c.name), spec.columns.map(c => c.width), spec.rows);
    spec.columns.forEach((col, i) => { if (col.format) for (let row = 8; row <= ws.rowCount; row++) if (typeof ws.getCell(row, i + 1).value === "number" || ws.getCell(row, i + 1).value instanceof Date) ws.getCell(row, i + 1).numFmt = col.format; });
    if (spec.name === "Indicators") m.kpis.forEach((k, i) => { [k.value, k.previous, k.target].forEach((v, c) => { ws.getCell(i + 8, c + 3).numFmt = workbookNumberFormat(v, k.unit); }); });
    if (spec.name === "Overview") spec.rows.forEach((r, i) => { if (typeof r[1] === "number") ws.getCell(i + 8, 2).numFmt = r[2] === "USD" ? "#,##0.00" : "#,##0"; if (r[1] instanceof Date) ws.getCell(i + 8, 2).numFmt = "yyyy-mm-dd hh:mm:ss"; });
  }
  return writer.finish();
}
